---
deployment:
  tasks:
    - export DEPLOYPATH=/home/luku8469/public_html/lukubara.com
    - /bin/cp -R companyprofile $DEPLOYPATH
    - /bin/cp -R lukubaracom $DEPLOYPATH
    - /bin/cp -R static $DEPLOYPATH
    - /bin/cp manage.py $DEPLOYPATH